# Generated by Django 5.2.7 on 2025-10-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes about the user.', verbose_name='Notes'),
        ),
    ]
